[package]
name = "cask-cli"
version = "0.1.0"
authors = ["Kenjiro Nakayama <nakayamakenjiro@gmail.com>"]

[dependencies]
clap = "~2.27"
cask = { git = "https://github.com/andresilva/cask" }
shrust = "0.0.4"
